<a href="https://colab.research.google.com/github/mehmetalivarol/time-series-analysis-with-lstm/blob/master/dynamicregressiondeneme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#import required packages
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.metrics import mean_squared_error
import sklearn

#read the data
df=pd.read_excel('/content/drive/My Drive/Colab Data/DO.linkterasend.xlsx')

print('Number of rows and columns:', df.shape)
df.head(5)

#check the dtypes
df.dtypes

Number of rows and columns: (761, 7)


Date               datetime64[ns]
Units                       int64
IsGunuKatsayi             float64
DayOfWeek                   int64
WorkDayOfWeek               int64
WorkDayOfMonth2             int64
GeriOdemeDurum             object
dtype: object

In [0]:
df=df.loc[:,['Date','Units','IsGunuKatsayi','DayOfWeek']]
df.set_index('Date',inplace=True)

In [0]:
#missing value treatment
cols = df.columns
for j in cols:
    for i in range(0,len(data)):
       if df[j][i] == -761:
           df[j][i] = df[j][i-1]



In [0]:
#creating the train and validation set
train = df[:int(0.8*(len(df)))]
valid = df[int(0.8*(len(df))):]

#fit the model
from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()

# make prediction on validation
prediction = model_fit.forecast(model_fit.y, steps=len(valid))

/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [0]:
#converting predictions to dataframe
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[cols])
for j in range(0,3):
    for i in range(0, len(prediction)):
       pred.iloc[i][j] = prediction[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', np.sqrt(mean_squared_error(pred[i], valid[i])))

rmse value for Units is :  1022.6631641025077
rmse value for IsGunuKatsayi is :  0.4104016846630699
rmse value for DayOfWeek is :  1.9988530904444908


In [0]:
#make final predictions
model = VAR(endog=df)
model_fit = model.fit()
yhat = model_fit.forecast(model_fit.y, steps=31)
print(yhat)



[[1.59620080e+03 8.07494129e-01 4.17428218e+00]
 [1.52264363e+03 7.03691508e-01 4.37922902e+00]
 [1.57528402e+03 6.89600975e-01 4.19630123e+00]
 [1.65159416e+03 7.08954960e-01 4.02282832e+00]
 [1.69326145e+03 7.25427292e-01 3.96027008e+00]
 [1.70143487e+03 7.30878482e-01 3.96692469e+00]
 [1.69595727e+03 7.29943822e-01 3.98827999e+00]
 [1.69033931e+03 7.27856785e-01 4.00033784e+00]
 [1.68822919e+03 7.26756961e-01 4.00235864e+00]
 [1.68840095e+03 7.26610841e-01 4.00039186e+00]
 [1.68909021e+03 7.26815133e-01 3.99856600e+00]
 [1.68949200e+03 7.26987475e-01 3.99791584e+00]
 [1.68956569e+03 7.27043782e-01 3.99799039e+00]
 [1.68950435e+03 7.27033462e-01 3.99821558e+00]
 [1.68944452e+03 7.27011452e-01 3.99834147e+00]
 [1.68942239e+03 7.26999974e-01 3.99836194e+00]
 [1.68942429e+03 7.26998509e-01 3.99834099e+00]
 [1.68943154e+03 7.27000680e-01 3.99832183e+00]
 [1.68943574e+03 7.27002487e-01 3.99831509e+00]
 [1.68943648e+03 7.27003070e-01 3.99831592e+00]
 [1.68943583e+03 7.27002957e-01 3.998318

/usr/local/lib/python3.6/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)
